name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  podspec:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: bundle update --bundler
    - run: bundle install
    - run: bundle exec pod lib lint
